# Generated by Django 4.2.23 on 2025-07-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='albumes_fotos'),
        ),
        migrations.AddField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='artistas_fotos'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canciones_fotos'),
        ),
    ]
