# Generated by Django 4.2.23 on 2025-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0004_albumpop_albumreggaeton'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistaPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='artistas_fotos')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistaReggaeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='artistas_fotos')),
            ],
        ),
        migrations.CreateModel(
            name='CancionPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('artista', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canciones_fotos')),
            ],
        ),
        migrations.CreateModel(
            name='CancionReggaeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('artista', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canciones_fotos')),
            ],
        ),
    ]
